apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: app-container
        image: 345852704676.dkr.ecr.us-east-1.amazonaws.com/webapp:v1
        env:
          - name: DATABASE
            value: employees
          - name: DBHOST
            value: "mysql-serv.final.svc.cluster.local"
          - name: DBPORT
            value: "3306"
          - name: DBPWD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: password
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                name: mysql
                key: username
          - name: BUCKETNAME      
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: bucket
          - name: BGIMG
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: bgimg
        resources:
          requests:
            cpu: 15m
          limits:
            cpu: 50m
        ports:
          - containerPort: 81
