apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: clo835
      containers:
      - name: app
        image: 329673269900.dkr.ecr.us-east-1.amazonaws.com/webapp:v0.1
      ports:
      - containerPort: 8080
