apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: application-hpa
  namespace: final
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 5