apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: employees
spec:
  type: NodePort
  ports:
    - port: 81
      targetPort: 81
      nodePort: 30000
  selector:
    app: employees